---
# tasks file for apigee-opdk-setup-local-repository
- name: Install rsync if its missing
  yum:
    name: rsync
    state: present

- name: First scp download attempt failed, trying with rsync
  synchronize:
    mode: pull
    src: '{{ apigeerepobasepath }}/{{ apigee_archive_name }}'
    dest: '{{ local_apigee_path }}/{{ apigee_archive_name }}'
  register: result

- name: Download archive status report
  debug:
    var: result
