---
# tasks file for opdk-setup-local-repository
- name: Download archive
  fetch:
    src: '{{ archive_path }}'
    dest: '{{ archive_name }}'
    flat: yes
  register: result

- name: Download archive status report
  debug:
    var: result
