---
# tasks file for apigee-opdk-setup-local-repository
- name: Update cache with key and value
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'apigee_archive_name', value: '{{ apigee_archive_name }}' }
  - { key: 'apigeerepobasepath', value: '{{ apigeerepobasepath }}' }


- name: Install rsync if its missing
  become: yes
  yum:
    name: rsync
    state: present

- name: Download with rsync
  become: no
  synchronize:
    mode: pull
    partial: yes
    src: '{{ apigeerepobasepath }}/{{ apigee_archive_name }}'
    dest: '{{ local_apigee_path }}/{{ apigee_archive_name }}'
  register: result

- name: Download archive status report
  debug:
    var: result
